package ar.edu.unq.desapp.grupoh.backenddesappapi.model;

public enum Criptos {
    ALICEUSDT,MATICUSDT,AXSUSDT,AAVEUSDT,ATOMUSDT,NEOUSDT,DOTUSDT,ETHUSDT,CAKEUSDT,
    BTCUSDT,BNBUSDT,ADAUSDT,TRXUSDT,AUDIOUSDT
}
